os:
  - linux

language: node_js
node_js:
  - '7'
  - '6'

# before_install:
#   - sudo add-apt-repository -y ppa:moti-p/cc
#   - sudo apt-get update
#   - sudo apt-get -y --reinstall --fix-missinginstall imagemagick
